In [11]:
import numpy as np
A0 = np.array([[4, 2, 1, 5], 
               [8, 7, 2, 10], 
               [4, 8, 3, 6],
               [6, 8, 4, 9]], dtype=float)

In [9]:
def algorithm_2_2(A):
    n = len(A)
    P, L, U = np.eye(n), np.zeros((n, n)), np.zeros((n, n))
    for i in range(n - 1):
        m = np.argmax(np.abs(A[i:, i])) + i
        if A[m, i] == 0:
            raise ValueError("matrix is singular.")
        else:
            if m != i:
                A[[i, m], :] = A[[m, i], :]
                L[[i, m], :] = L[[m, i], :]
                P[[i, m], :] = P[[m, i], :]
            for j in range(i + 1, n):
                L[j, i] = A[j, i] / A[i, i]

            for j in range(i, n):
                U[i, j] = A[i, j]

            for j in range(i + 1, n):
                for k in range(i + 1, n):
                    A[j, k] -= L[j, i] * U[i, k]

    P = P.T
    L += np.eye(n)
    U[-1, -1] = A[-1, -1]
    return A, P, L, U

In [12]:
A, P, L, U = algorithm_2_2(A0.copy())
print(A0)
print(P)
print(L)
print(U)
print(A0 - P@L@U)

[[  4.   2.   1.   5.]
 [  8.   7.   2.  10.]
 [  4.   8.   3.   6.]
 [  6.   8.   4.   9.]]
[[ 0.  0.  0.  1.]
 [ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]]
[[ 1.          0.          0.          0.        ]
 [ 0.5         1.          0.          0.        ]
 [ 0.75        0.61111111  1.          0.        ]
 [ 0.5        -0.33333333  0.52173913  1.        ]]
[[  8.           7.           2.          10.        ]
 [  0.           4.5          2.           1.        ]
 [  0.           0.           1.27777778   0.88888889]
 [  0.           0.           0.          -0.13043478]]
[[  0.00000000e+00   0.00000000e+00   0.00000000e+00  -8.88178420e-16]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]]


In [13]:
def algorithm_2_3(A):
    n = len(A)
    P = np.eye(n)

    for i in range(n - 1):

        m = np.argmax(np.abs(A[i:, i])) + i

        if A[m, i] == 0:
            raise ValueError("matrix is singular.")
        else:
            if m != i:
                A[[i, m], :] = A[[m, i], :]
                P[[i, m], :] = P[[m, i], :]

            for j in range(i + 1, n):
                A[j, i] = A[j, i] / A[i, i]

            for j in range(i + 1, n):
                for k in range(i + 1, n):
                    A[j, k] -= A[j, i] * A[i, k]

    P = P.T
    L = np.tril(A, -1) + np.eye(n)
    U = np.triu(A, 0)
    return A, P, L, U

In [14]:
A, P, L, U = algorithm_2_3(A0.copy())
print(A0)
print(P)
print(L)
print(U)
print(A0 - P@L@U)

[[  4.   2.   1.   5.]
 [  8.   7.   2.  10.]
 [  4.   8.   3.   6.]
 [  6.   8.   4.   9.]]
[[ 0.  0.  0.  1.]
 [ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]]
[[ 1.          0.          0.          0.        ]
 [ 0.5         1.          0.          0.        ]
 [ 0.75        0.61111111  1.          0.        ]
 [ 0.5        -0.33333333  0.52173913  1.        ]]
[[  8.           7.           2.          10.        ]
 [  0.           4.5          2.           1.        ]
 [  0.           0.           1.27777778   0.88888889]
 [  0.           0.           0.          -0.13043478]]
[[  0.00000000e+00   0.00000000e+00   0.00000000e+00  -8.88178420e-16]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]]


In [16]:
def algorithm_2_4(A):
    n = len(A)
    P = np.eye(n)

    for i in range(n - 1):
        m = np.argmax(np.abs(A[i:, i])) + i

        if A[m, i] == 0:
            raise ValueError("matrix is singular.")
        else:
            if m != i:
                A[[i, m], :] = A[[m, i], :]
                P[[i, m], :] = P[[m, i], :]

            A[(i + 1):, i] = A[(i + 1):, i] / A[i, i]
            A[(i + 1):, (i + 1):] -= A[(i + 1):, i].reshape(-1, 1)*A[i, (i + 1):]

    P = P.T
    L = np.tril(A, -1) + np.eye(n)
    U = np.triu(A, 0)
    return A, P, L, U

In [17]:
A, P, L, U = algorithm_2_4(A0.copy())
print(A0)
print(P)
print(L)
print(U)
print(A0 - P@L@U)

[[  4.   2.   1.   5.]
 [  8.   7.   2.  10.]
 [  4.   8.   3.   6.]
 [  6.   8.   4.   9.]]
[[ 0.  0.  0.  1.]
 [ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]]
[[ 1.          0.          0.          0.        ]
 [ 0.5         1.          0.          0.        ]
 [ 0.75        0.61111111  1.          0.        ]
 [ 0.5        -0.33333333  0.52173913  1.        ]]
[[  8.           7.           2.          10.        ]
 [  0.           4.5          2.           1.        ]
 [  0.           0.           1.27777778   0.88888889]
 [  0.           0.           0.          -0.13043478]]
[[  0.00000000e+00   0.00000000e+00   0.00000000e+00  -8.88178420e-16]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]]
