In [18]:
import numpy as np
def lu(A):
    if not A.shape[0] == A.shape[1]:
        raise ValueError("Input matrix must be square")
    n = A.shape[0]
    L = np.zeros((n, n), dtype=np.float)
    U = np.zeros((n, n), dtype=np.float)
    U[:] = A
    np.fill_diagonal(L, 1)
    for i in range(n-1):
        for j in range(i+1, n):
            L[j, i] = U[j, i]/U[i, i]
            U[j, i:] = U[j, i:] - L[j, i]*U[i, i:]
            U[j, i] = 0
    return(L, U)

In [19]:
A = np.matrix([[1, 1, 1], [0, 4, -1], [2, -2, 1]])

In [20]:
lu(A)

(array([[ 1.,  0.,  0.],
        [ 0.,  1.,  0.],
        [ 2., -1.,  1.]]), array([[ 1.,  1.,  1.],
        [ 0.,  4., -1.],
        [ 0.,  0., -2.]]))

In [21]:
B = np.matrix([[0.0001, 1], [1, 1]])

In [22]:
lu(B)

(array([[  1.00000000e+00,   0.00000000e+00],
        [  1.00000000e+04,   1.00000000e+00]]),
 array([[  1.00000000e-04,   1.00000000e+00],
        [  0.00000000e+00,  -9.99900000e+03]]))