In [21]:
import numpy as np
def cgs_qr(A):
    m, n = A.shape
    A = A.copy()
    Q = np.zeros((m,n))
    R = np.zeros((n,n))
    for k in range(n):
        R[k,k] = np.linalg.norm(A[:,k],ord=2)
        Q[:,k] = A[:,k]/R[k, k]
        R[k,k+1:] = np.dot(Q[:,k].T, A[:,k+1:])
        A[:,k+1:] = A[:,k+1:] - np.dot(Q[:,k:k+1], R[k:k+1, k+1:])
    return Q, R

In [22]:
B = np.array([[6, 5, 0], [5, -1, 4], [5, 1, -14], [0, 4, 3]], dtype=np.float)

In [23]:
cgs_qr(B)

(array([[ 0.64699664,  0.50964401,  0.17989978],
        [ 0.53916387, -0.48110395,  0.57427139],
        [ 0.53916387, -0.13046887, -0.79015113],
        [ 0.        ,  0.70127016,  0.1162309 ]]),
 array([[  9.2736185 ,   3.2349832 ,  -5.39163866],
        [  0.        ,   5.70393581,   2.00595884],
        [  0.        ,   0.        ,  13.70789414]]))

In [24]:
import numpy as np
def mgs_qr(A):
    m, n = A.shape
    A = A.copy()
    Q = np.zeros((m,n))
    R = np.zeros((n,n))
    for k in range(n):
        R[k,k] = np.linalg.norm(A[:,k],ord=2)
        Q[:,k] = A[:,k]/R[k, k]
        R[k,k+1:] = np.dot(Q[:,k].T, Q[:,k+1:])
        A[:,k+1:] = A[:,k+1:] - np.dot(Q[:,k:k+1], R[k:k+1, k+1:])
    return Q, R

In [25]:
C = np.array([[6, 5, 0], [5, -1, 4], [5, 1, -14], [0, 4, 3]], dtype=np.float)

In [26]:
mgs_qr(C)

(array([[ 0.64699664,  0.76249285,  0.        ],
        [ 0.53916387, -0.15249857,  0.26906912],
        [ 0.53916387,  0.15249857, -0.94174191],
        [ 0.        ,  0.60999428,  0.20180184]]),
 array([[  9.2736185 ,   0.        ,   0.        ],
        [  0.        ,   6.55743852,   0.        ],
        [  0.        ,   0.        ,  14.86606875]]))