In [2]:
import numpy as np
def cgs_qr(A):
    m, n = A.shape
    A = A.copy()
    Q = np.zeros((m,n))
    R = np.zeros((n,n))
    for k in range(n):
        R[k,k] = np.linalg.norm(A[:,k],ord=2)
        Q[:,k] = A[:,k]/R[k, k]
        R[k,k+1:] = np.dot(Q[:,k].T, A[:,k+1:])
        A[:,k+1:] = A[:,k+1:] - np.dot(Q[:,k:k+1], R[k:k+1, k+1:])
    return Q, R

In [3]:
B = np.array([[6, 5, 0], [5, -1, 4], [5, 1, -14], [0, 4, 3]], dtype=np.float)

In [8]:
Q, R = cgs_qr(B)
Q@R

array([[  6.00000000e+00,   5.00000000e+00,   7.93587073e-20],
       [  5.00000000e+00,  -1.00000000e+00,   4.00000000e+00],
       [  5.00000000e+00,   1.00000000e+00,  -1.40000000e+01],
       [  0.00000000e+00,   4.00000000e+00,   3.00000000e+00]])

In [20]:
import numpy as np
def mgs_qr(A):
    m, n = A.shape
    A = A.copy()
    Q = np.zeros((m,n))
    R = np.zeros((n,n))
    for i in range(n):
        Q[:,i] = A[:,i]
        for j in range(i):
            R[j, i] = np.dot(Q[:, j], Q[:, i])
            Q[:, i] -= R[j, i]*Q[:, j]
        R[i, i] = np.linalg.norm(Q[:, i], ord=2)
        Q[:, i] /= R[i, i]
    return Q, R

In [23]:
Q, R=mgs_qr(B)
Q.transpose()@Q
Q@R

array([[  6.00000000e+00,   5.00000000e+00,   7.93587073e-20],
       [  5.00000000e+00,  -1.00000000e+00,   4.00000000e+00],
       [  5.00000000e+00,   1.00000000e+00,  -1.40000000e+01],
       [  0.00000000e+00,   4.00000000e+00,   3.00000000e+00]])

In [35]:
import numpy as np
def cgs_qr1(A):
    m, n = A.shape
    A = A.copy()
    Q = np.zeros((m,n))
    R = np.zeros((n,n))
    R[0, 0] = np.linalg.norm(A[:, 0])
    Q[:, 0] = A[:, 0]/R[0, 0]
    for i in range(1, n):
        Q[:, i] = A[:, i]
        R[0:i, i] = A[:, i]@Q[:, 0:i]
        Q[:, i] -= Q[:, 0:i]@R[0:i, i]
        R[i, i] = np.linalg.norm(Q[:, i])
        Q[:, i] /= R[i, i]
    return Q, R

In [37]:
Q, R = cgs_qr1(B)
Q.transpose()@Q

array([[  1.00000000e+00,   1.27587578e-16,  -6.38676574e-17],
       [  1.27587578e-16,   1.00000000e+00,   1.65877472e-17],
       [ -6.38676574e-17,   1.65877472e-17,   1.00000000e+00]])